const toString = {
    username:String,
    name:{
        fname:String,
        lname:String
    },
    profilePhoto:String,
    email:String,
    password:String,
    class:{type:String, enum:["A","B","C","D"]},
    subjects:{
        subject1:{
            subjectName:String,
            subjectCode:String,
            attendance:Number,
            marks:Number
        },
        subject2:{
            subjectName:String,
            subjectCode:String,
            attendance:Number,
            marks:Number
        },
        subject3:{
            subjectName:String,
            subjectCode:String,
            attendance:Number,
            marks:Number
        },
        subject4:{
            subjectName:String,
            subjectCode:String,
            attendance:Number,
            marks:Number
        },
        subject5:{
            subjectName:String,
            subjectCode:String,
            attendance:Number,
            marks:Number
        },
        subject6:{
            subjectName:String,
            subjectCode:String,
            attendance:Number,
            marks:Number
        }
    },
    teachers:{
        // holds the teacher ids for each subject
        subject1:String,
        subject2:String,
        subject3:String,
        subject4:String,
        subject5:String,
        subject6:String,
    }
}


console.log(JSON.stringify(toString))